apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-vlfn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/integration-e2e-tenant/integ-app-mqdi/devfile-sample-python-basic-vlfn@sha256:68ea759ec64c1f6dc856a29cba854520825f54347269c09167f3052dd65736bc
        name: my-python
        resources: {}
status: {}
